<?php return array (
  'QQ_APP_KEY' => '',
  'QQ_APP_SECRET' => '',
  'QQ_CALLBACK' => '',
  'SINA_APP_KEY' => '',
  'SINA_APP_SECRET' => '',
  'SINA_CALLBACK' => '',
  'MG_TITLENAME' => '博客',
  'MG_MAIL' => 'chengwan188@163.com',
  'MG_ICP' => '京ICP备1000000号',
  'MG_COPYRIGHT' => '© blog 2016',
  'CP_EMAIL_FROM_NAME' => '悟空',
  'CP_EMAIL_SMTP' => 'smtp.163.com',
  'CP_EMAIL_USERNAME' => 'chengwan188@163.com',
  'CP_EMAIL_PASSWORD' => 'qqq222222',
)?>